# Basic Problems

1. Variable Swap: Write a Python program to swap the values of two variables without using a temporary variable.

In [1]:
v1=10
v2=20
print('First variable value: ',v1)
print('Second variable value: ',v2)

#addition and subtraction
#v1=v1+v2
#v2=v1-v2
#v1=v1-v2

#product and division
#v1=v1*v2
#v2=v1//v2
#v1=v1//v2

#xor or bit operation
v1=v1^v2
v2=v1^v2
v1=v1^v2

print('First variable value: ',v1)
print('Second variable value: ',v2)

First variable value:  10
Second variable value:  20
First variable value:  20
Second variable value:  10


2. Even or Odd: Write a Python program that takes an integer as input and prints whether it is even or odd.

In [2]:
#number = int(input('Type any number: '))
number = 5
if number%2==0:
    print('Even Number')
else:
    print('Odd Number')

Odd Number


3. String Reverse: Write a Python function to reverse a given string and return the reversed string.

In [3]:
def reverse_string(string_var):
    char_list = list(string_var)
    str_length = len(char_list)-1
    rev_string_var = ''
    while str_length>-1:
        rev_string_var += char_list[str_length]
        str_length-=1
    return rev_string_var

string_var = 'Mohammad Shihab Uddin'
print(string_var)
print(reverse_string(string_var))

Mohammad Shihab Uddin
niddU bahihS dammahoM


4. Type Conversion: Given a list of integers, write a Python program to convert each element of the list to a string.

In [4]:
list_int = [1,2,3,4,5,6]
print(list_int)
str_var = ''
for i in list_int:
    str_var += ''.join(str(i))
print(str_var)

[1, 2, 3, 4, 5, 6]
123456


5. Temperature Converter: Write a Python program that converts a temperature in Celsius to Fahrenheit. Take the Celsius temperature as input from the user.

In [5]:
#celsius = float(input('Type temperature in Celsius: '))
celsius = 32
fahrenheit = (celsius * (9/5)) + 32 
print('Temperature in fahrenheit: ',fahrenheit)

Temperature in fahrenheit:  89.6


6. Data Type Checker: Write a Python function that takes a variable as input and returns the data type of the variable as a string (e.g., “int”, “float”, “str”, “list”, etc.).

In [6]:
def get_data_tupe(data):
    return type(data).__name__

list_data = [12,1.21,12+3j,True,'abc',[1,2,2],(1,2,3),{1,2,3},{1:2,3:4,5:6}]
print(list_data)
for i in list_data:
    print(get_data_tupe(i),end=', ')


[12, 1.21, (12+3j), True, 'abc', [1, 2, 2], (1, 2, 3), {1, 2, 3}, {1: 2, 3: 4, 5: 6}]
int, float, complex, bool, str, list, tuple, set, dict, 

7. String Palindrome: Write a Python function to check if a given string is a palindrome or not.

In [7]:
def check_palindrome(data):
    char_list = list(data)
    str_length = len(char_list)
    mid_length = str_length//2
    i = 0
    while i<mid_length:
        if char_list[i]!=char_list[str_length-1]:
            return False
        i = i + 1
        str_length = str_length - 1
    return True

if check_palindrome('madam'):
    print('String is a palindrome')
else:
    print('String is not a palindrome')


String is a palindrome


9. String Concatenation: Write a Python program that takes two strings as input and concatenates them into a single string without using the `+` operator.

In [8]:
#str_1 = input('type string 1: ')
#str_2 = input('type string 2: ')
str_1 = 'shihab'
str_2 = ' uddin'
str_3="".join([str_1,str_2])
print(str_3)

shihab uddin


10. Typecasting Challenge: Given three variables: `a = ‘100’`, `b = 25`, and `c = ‘10.5’`, write a Python program to perform the following operations and print the results:

– Convert `a` to an integer and add it to `b`.

– Convert `c` to a float and subtract it from the result of the first operation.

– Convert the final result to a string and concatenate it with the string ” is the answer.”

In [9]:
a = '100'
b=25
c='10.5'
print('Add a and b ',int(a)+b)
print('subtract a and b from c ',(int(a)+b)-float(c))
print('Result ','is the answer '+str((int(a)+b)-float(c)))

Add a and b  125
subtract a and b from c  114.5
Result  is the answer 114.5


# Python Conditional Statements

11. Positive, Negative, or Zero: Write a Python program that takes a number as input and prints whether it is positive, negative, or zero.

In [10]:
#number = int(input('Type a number: '))
number = 2
if number>0:
    print('Positive Number')
elif number<0:
    print('Negative Number')
else:
    print('Zero')

Positive Number


12. Largest of Three Numbers: Write a Python program that takes three numbers as input and prints the largest among them.

In [11]:
#num_1 =int(input('Type number 1: '))
#num_2 =int(input('Type number 2: '))
#num_3 =int(input('Type number 3: '))
num_1 = 5
num_2 = 8
num_3 = 7
if num_1>num_2 and num_1>num_3:
    print(num_1,' is largest')
elif num_2>num_3:
    print(num_2,' is largest')
else:
    print(num_3,' is largest')


8  is largest


13. Leap Year Checker: Write a Python program that takes a year as input and determines if it is a leap year or not.

In [12]:
#year =int(input('Type year: '))
year = 2000
if (year%4==0 and year%100!=0) or (year%400==0 and year%100==0):
    print(year,' is leap year')
else:
    print(year,' is not leap year')


2000  is leap year


14. Grades Classification: Write a Python program that takes a student’s percentage as input and prints their corresponding grade according to the following criteria:

– 90% or above: A+
– 80-89%: A
– 70-79%: B
– 60-69%: C
– Below 60%: Fail

In [13]:
#marks =int(input('Type marks: '))
marks = 67
print('Grade: ',end='')
if marks>=90:
    print('A+')
elif marks>=80:
    print('A')
elif marks>=70:
    print('B')
elif marks>=60:
    print('C')
else:
    print('Fail')


Grade: C


15. Vowel or Consonant: Write a Python program that takes a single character as input and determines whether it is a vowel or a consonant.

In [14]:
#char =input('Type character: ')
char = 'u'
if char=='a' or char=='e' or char=='i' or char=='o' or char=='u':
    print(char,' is a vowel')
else:
    print(char,' is a consonant')


u  is a vowel


16. Time Classification: Write a Python program that takes the time in hours (24-hour format) as input and prints “Good Morning”, “Good Afternoon”, “Good Evening”, or “Good Night” based on the time.

In [15]:
#hour =int(input('Type hours (1-24): '))
hour = 13
if hour>=5 and hour<12:
    print('Good Morning')
elif hour>=12 and hour<17:
    print('Good Afternoon')
elif hour>=17 and hour<21:
    print('Good Evening')
else:
    print('Good Night')


Good Afternoon


17. Triangle Type Checker: Write a Python program that takes three sides of a triangle as input and determines whether it forms an equilateral, isosceles, or scalene triangle.

In [16]:
#side_1 =int(input('Type side 1: '))
#side_2 =int(input('Type side 2: '))
#side_3 =int(input('Type side 3: '))
side_1 = 6
side_2 = 5
side_3 = 6
if side_1==side_2 and side_2==side_3:
    print('This is a equilateral triangle')
elif  side_1==side_2 or side_2==side_3 or side_1==side_3:
    print('This is a isosceles triangle')
else:
    print('This is a scalene triangle')


This is a isosceles triangle


18. Quadratic Equation Solver: Write a Python program that takes the coefficients (a, b, c) of a quadratic equation as input and calculates and prints the real roots (if they exist) or a message indicating the complex roots.


In [17]:
import cmath

#a = int(input('Type value a: '))
#b = int(input('Type value b: '))
#c = int(input('Type vakue c: '))

a = 8
b = 6
c = 4

d = (b**2) - (4*a*c)

sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

The solution are (-0.375-0.5994789404140899j) and (-0.375+0.5994789404140899j)


19. Number Ranges: Write a Python program that takes an integer as input and prints whether the number falls within the ranges: 0-50, 51-100, 101-150, or above 150.

In [18]:
#number =int(input('Type number: '))
number = 76
if number>0 and number<=50:
    print('Range: 0-50')
elif number>50 and number<=100:
    print('Range: 51-100')
elif number>100 and number<=150:
    print('Range: 101-150')
elif number>150:
    print('Range: above 150')
else:
    print('Invalid Range')


Range: 51-100


# For & While Loops

20. Sum of N Numbers: Write a Python program using a for loop to calculate the sum of the first N natural numbers, where N is taken as input from the user.

In [19]:
#number = int(input('type number: '))
number = 10
sum_value = 0
for i in range(1,number+1):
    sum_value+=i
print('Sum of ',number,' Numbers: ',sum_value)


Sum of  10  Numbers:  55


21. Factorial Calculator: Write a Python program using a while loop to calculate the factorial of a given number N.

In [20]:
#number = int(input('type number: '))
number = 5
i = number
factorial = 1
while i>0:
    factorial*=i
    i-=1
print(number,'! (factorial) = ',factorial)

5 ! (factorial) =  120


22. Table of a Number: Write a Python program using a for loop to print the multiplication table of a given number N.

In [21]:
#number = int(input('type number: '))
number = 7
i = 1
while i<11:
    print(number,' X ',i,' = ',i*number)
    i+=1


7  X  1  =  7
7  X  2  =  14
7  X  3  =  21
7  X  4  =  28
7  X  5  =  35
7  X  6  =  42
7  X  7  =  49
7  X  8  =  56
7  X  9  =  63
7  X  10  =  70


23. Count Digits in a Number: Write a Python program using a while loop to count the number of digits in a given integer N.

In [22]:
#number = int(input('type number: '))
number = 456123
count_digit = 0
while number!=0:
    number=number//10
    count_digit+=1
print('Number of digit: ',count_digit)

Number of digit:  6


24. Fibonacci Sequence: Write a Python program using a for loop to generate the Fibonacci sequence up to a given limit N.

In [23]:
#number = int(input('type number: '))
number = 10
i = 1
fib_1 = 1
fib_2 = 1
print(fib_1,end=' ')
print(fib_2,end=' ')
while i<=number-2:
    temp = fib_1 + fib_2
    fib_1 = fib_2
    fib_2 = temp
    print(fib_2,end=' ')
    i = i + 1

1 1 2 3 5 8 13 21 34 55 

25. Sum of Even Numbers: Write a Python program using a while loop to calculate the sum of all even numbers between 1 and N, where N is taken as input from the user.

In [24]:
#number = int(input('type number: '))
number = 10
sum_even_value = 0
for i in range(2,number+1,2):
    sum_even_value+=i
print('Sum of even number: ',sum_even_value)

Sum of even number:  30


26. Print Patterns: Write a Python program using nested for loops to print various patterns, such as a right-angled triangle, an inverted right-angled triangle, and so on.

In [25]:
for i in range(1,6):
    for j in range(1,i+1):
        print('*',end='')
    print()
print('----------------')
for i in range(1,6):
    for j in range(1,7-i):
        print('*',end='')
    print()
print('----------------')
for i in range(1,6):
    for j in range(1,6-i):
        print(' ',end='')
    for j in range(1,i+1):
        print('*',end='')
    print()
print('----------------')
for i in range(1,6):
    for j in range(1,i):
        print(' ',end='')
    for j in range(1,7-i):
        print('*',end='')
    print()
print('----------------')

*
**
***
****
*****
----------------
*****
****
***
**
*
----------------
    *
   **
  ***
 ****
*****
----------------
*****
 ****
  ***
   **
    *
----------------


27. Prime Number Checker: Write a Python program using a while loop to check if a given number N is prime or not.

In [26]:
#number = int(input('type number: '))
number = 23
i = 2
is_prime = True
while i<number//2+1:
    if number%i==0:
        is_prime = False
        break;
    i+=1
if is_prime:
    print('Prime Number')
else:
    print('Not prime Number')


Prime Number


28. List Manipulation: Given a list of integers, write a Python program using a for loop to find the sum, average, maximum, and minimum values in the list.

In [27]:
number_list = [12,30,75,9,42,80]
sum_val = 0
max_val = 0
min_val = 9999
count_val = len(number_list)
for i in number_list:
    sum_val+=i
    if max_val<i:
        max_val=i
    if min_val>i:
        min_val=i
avg_val = sum_val/count_val
print('Sum: ',sum_val)
print('Average: ',round(avg_val, 2))
print('Maximum: ',max_val)
print('Minimum: ',min_val)

Sum:  248
Average:  41.33
Maximum:  80
Minimum:  9


29. Reverse String: Write a Python program using a while loop to reverse a given string.

In [28]:
my_string = "Mohammad Shihab Uddin"
print(my_string)
str_len = len(my_string)-1
while str_len>-1:
    print(my_string[str_len],end='')
    str_len-=1


Mohammad Shihab Uddin
niddU bahihS dammahoM

30. Multiplication Table: Write a Python program using nested loops to print the multiplication table from 1 to 10.

In [29]:
for i in range(1,11):
    for j in range(1,11):
        print(i,' X ',j,' = ',i*j)
    print()

1  X  1  =  1
1  X  2  =  2
1  X  3  =  3
1  X  4  =  4
1  X  5  =  5
1  X  6  =  6
1  X  7  =  7
1  X  8  =  8
1  X  9  =  9
1  X  10  =  10

2  X  1  =  2
2  X  2  =  4
2  X  3  =  6
2  X  4  =  8
2  X  5  =  10
2  X  6  =  12
2  X  7  =  14
2  X  8  =  16
2  X  9  =  18
2  X  10  =  20

3  X  1  =  3
3  X  2  =  6
3  X  3  =  9
3  X  4  =  12
3  X  5  =  15
3  X  6  =  18
3  X  7  =  21
3  X  8  =  24
3  X  9  =  27
3  X  10  =  30

4  X  1  =  4
4  X  2  =  8
4  X  3  =  12
4  X  4  =  16
4  X  5  =  20
4  X  6  =  24
4  X  7  =  28
4  X  8  =  32
4  X  9  =  36
4  X  10  =  40

5  X  1  =  5
5  X  2  =  10
5  X  3  =  15
5  X  4  =  20
5  X  5  =  25
5  X  6  =  30
5  X  7  =  35
5  X  8  =  40
5  X  9  =  45
5  X  10  =  50

6  X  1  =  6
6  X  2  =  12
6  X  3  =  18
6  X  4  =  24
6  X  5  =  30
6  X  6  =  36
6  X  7  =  42
6  X  8  =  48
6  X  9  =  54
6  X  10  =  60

7  X  1  =  7
7  X  2  =  14
7  X  3  =  21
7  X  4  =  28
7  X  5  =  35
7  X  6  =  42
7  X  7  =  49
7  X

31. Print Patterns: Write a Python program using nested loops to print the following pattern:
*/**/***/****/*****  


In [30]:
for i in range(1,6):
    for j in range(1,i+1):
        print('*',end='')
    print()

*
**
***
****
*****


32. Matrix Multiplication: Write a Python program using nested loops to multiply two matrices.

In [31]:
from array import *
A = [[1,1,1],[2,2,2],[3,3,3]]
B = [[1,1,1],[2,2,2],[3,3,3]]
C = [[0,0,0],[0,0,0],[0,0,0]]
print('----A----') 
for i in range(0,3):
    for j in range(0,3):
        print(A[i][j],end=' ')
    print()
print('----B----') 
for i in range(0,3):
    for j in range(0,3):
        print(B[i][j],end=' ')
    print()
print('----A X B----') 
i=0
while i<3:  
    j=0
    while j<3:
        k=0
        while k<3:
            C[i][j]+=A[i][k]*B[k][j]
            k+=1
        j+=1
    i+=1
for i in range(0,3):
    for j in range(0,3):
        print(C[i][j],end=' ')
    print()



----A----
1 1 1 
2 2 2 
3 3 3 
----B----
1 1 1 
2 2 2 
3 3 3 
----A X B----
6 6 6 
12 12 12 
18 18 18 


In [32]:
import numpy as np
A = np.array([[1,1,1],[2,2,2],[3,3,3]])
B = np.array([[1,1,1],[2,2,2],[3,3,3]])
C = np.dot(A,B)
print(A)
print(B)
print(C)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[ 6  6  6]
 [12 12 12]
 [18 18 18]]


33. Chessboard Pattern: Write a Python program using nested loops to print a chessboard pattern (alternating “X” and “O” characters) of size 8×8.34. Number Pyramid: Write a Python program using nested loops to print a number pyramid like the following:

1
22
333
4444
55555

In [33]:
for i in range(1,6):
    for j in range(1,i+1):
        print(i,end='')
    print()


1
22
333
4444
55555


# List Problems:

34. List Sum: Write a Python program to find the sum of all elements in a given list of integers.

In [34]:
number_list = [12,30,75,9,42,80]
sum_val = 0
for i in number_list:
    sum_val+=i
print('Sum: ',sum_val)


Sum:  248


35. List Average: Write a Python program to calculate the average of all elements in a given list of integers.

In [35]:
number_list = [12,30,75,9,42,80]
sum_val = 0
count_val = len(number_list)
for i in number_list:
    sum_val+=i
avg_val = sum_val/count_val
print('Average: ',round(avg_val,2))


Average:  41.33


36. List Max and Min: Write a Python program to find the maximum and minimum values in a given list of integers.

In [36]:
number_list = [12,30,75,9,42,80]
max_val = 0
min_val = 9999
for i in number_list:
    if max_val<i:
        max_val=i
    if min_val>i:
        min_val=i
print('Maximum: ',max_val)
print('Minimum: ',min_val)

Maximum:  80
Minimum:  9


37. List Sorting: Write a Python program to sort a list of integers in ascending order.

In [37]:
number_list = [12,30,75,9,42,80]
print('List: ',number_list)
count_val = len(number_list)
i=1
while i<count_val:
    j=0
    while count_val-i>j:
        if number_list[j]>number_list[j+1]:
            temp = number_list[j]
            number_list[j]=number_list[j+1]
            number_list[j+1]= temp
        j+=1
    i+=1
print('Sorted List: ',number_list)

List:  [12, 30, 75, 9, 42, 80]
Sorted List:  [9, 12, 30, 42, 75, 80]


In [38]:
number_list = [12,30,75,9,42,80]
print('List: ',number_list)
number_list.sort()
print('Sorted List: ',number_list)

List:  [12, 30, 75, 9, 42, 80]
Sorted List:  [9, 12, 30, 42, 75, 80]


38. List Filtering: Given a list of integers, write a Python program to create a new list that contains only the even numbers from the original list.

In [39]:
number_list = [12,30,75,9,42,80]
print('List: ',number_list)
new_list = []
i=0
while i<count_val:
    if number_list[i]%2==0:
        new_list.append(number_list[i])
    i+=1
print('Even List: ',new_list)

List:  [12, 30, 75, 9, 42, 80]
Even List:  [12, 30, 42, 80]


39. List Reversal: Write a Python program to reverse a given list without using any built-in functions.

In [40]:
number_list = [12,30,75,9,42,80]
print('List: ',number_list)
new_list = []
i=count_val = len(number_list)-1
while i>-1:
    new_list.append(number_list[i])
    i-=1
print('Revers List: ',new_list)

List:  [12, 30, 75, 9, 42, 80]
Revers List:  [80, 42, 9, 75, 30, 12]


In [41]:
number_list = [12,30,75,9,42,80]
print('List: ',number_list)
number_list.reverse()
print('Sorted List: ',number_list)

List:  [12, 30, 75, 9, 42, 80]
Sorted List:  [80, 42, 9, 75, 30, 12]


40. List Manipulation: Given two lists of integers, write a Python program to create a new list that contains elements common to both lists.

In [42]:
number_list_1 = [12,30,75,9,42,80]
number_list_2 = [12,40,75,8,52,80]
print('List: ',number_list_1)
print('List: ',number_list_2)
new_list = []
i=0
while i<len(number_list):
    if number_list_1[i]==number_list_2[i]:
        new_list.append(number_list_1[i])
    i+=1
print('Common in Lists: ',new_list)

List:  [12, 30, 75, 9, 42, 80]
List:  [12, 40, 75, 8, 52, 80]
Common in Lists:  [12, 75, 80]


In [43]:
number_list_1 = [12,30,75,9,42,80]
number_list_2 = [12,40,75,8,52,80]
print('List: ',number_list_1)
print('List: ',number_list_2)
new_list = []
s1 = set(number_list_1)
s2 = set(number_list_2)
new_list = list(s1.intersection(s2))
print('Common in Lists: ',new_list)

List:  [12, 30, 75, 9, 42, 80]
List:  [12, 40, 75, 8, 52, 80]
Common in Lists:  [80, 75, 12]


41. List Element Count: Write a Python program to count the occurrences of a specific element in a given list.



In [44]:
number_list = [12,3,12,9,42,80,3,3,9]
print('List: ',number_list)
count_val = len(number_list)
new_number_list = []
count_number_list = []
i=0
while i<count_val:
    j=i+1
    count_number = 1
    if number_list[i]!=0:
        new_number_list.append(number_list[i])
        while j<count_val:   
            if number_list[i]==number_list[j]:
                number_list[j]=0
                count_number+=1
            j+=1  
        number_list[i]=0
        count_number_list.append(count_number)
    i+=1
print('New List: ',new_number_list)
print('Count List: ',count_number_list)

List:  [12, 3, 12, 9, 42, 80, 3, 3, 9]
New List:  [12, 3, 9, 42, 80]
Count List:  [2, 3, 2, 1, 1]


In [45]:
number_list = [12,3,12,9,42,80,3,3,9]
print('List: ',number_list)
count_val = len(number_list)
count_number=0
i=0
specific_value = 12
while i<count_val:
    if number_list[i]==specific_value:
        count_number+=1
    i+=1
print('Specific value: ',specific_value,'is',count_number,'times in the list')

List:  [12, 3, 12, 9, 42, 80, 3, 3, 9]
Specific value:  12 is 2 times in the list


42. List Duplicates Removal: Write a Python program to remove duplicates from a given list while preserving the order of the elements.

In [46]:
number_list = [12,3,12,9,42,80,3,3,9]
print('List: ',number_list)
count_val = len(number_list)
new_number_list = []
i=0
while i<count_val:
    j=i+1
    count_number = 1
    if number_list[i]!=0:
        new_number_list.append(number_list[i])
        while j<count_val-1:   
            if number_list[i]==number_list[j]:
                number_list[j]=0
            j+=1  
        number_list[i]=0
    i+=1
print('New List(remove duplicate): ',new_number_list)

List:  [12, 3, 12, 9, 42, 80, 3, 3, 9]
New List(remove duplicate):  [12, 3, 9, 42, 80, 9]


43. List Comprehension: Given a list of integers, write a Python program to create a new list that contains the squares of the elements using list comprehension.

In [47]:
number_list = [2,7,3,9,6,1,5]
print('List: ',number_list)
new_number_list = [i**2 for i in number_list]
print('New List: ',new_number_list)

List:  [2, 7, 3, 9, 6, 1, 5]
New List:  [4, 49, 9, 81, 36, 1, 25]


# Nested List Problems:

44. Matrix Addition: Write a Python program to add two matrices represented as nested lists.

In [48]:
A = [[1,1,1],[2,2,2],[3,3,3]]
B = [[1,1,1],[2,2,2],[3,3,3]]
C = [[0,0,0],[0,0,0],[0,0,0]]
print('----A----') 
for i in range(0,3):
    for j in range(0,3):
        print(A[i][j],end=' ')
    print()
print('----B----') 
for i in range(0,3):
    for j in range(0,3):
        print(B[i][j],end=' ')
    print()
print('----A + B----') 
i=0
while i<3:  
    j=0
    while j<3:
        C[i][j]=A[i][j]+B[i][j]
        j+=1
    i+=1
for i in range(0,3):
    for j in range(0,3):
        print(C[i][j],end=' ')
    print()


----A----
1 1 1 
2 2 2 
3 3 3 
----B----
1 1 1 
2 2 2 
3 3 3 
----A + B----
2 2 2 
4 4 4 
6 6 6 


In [49]:
import numpy as np
A = np.array([[1,1,1],[2,2,2],[3,3,3]])
B = np.array([[1,1,1],[2,2,2],[3,3,3]])
C = np.add(A,B)
print(A)
print(B)
print(C)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[2 2 2]
 [4 4 4]
 [6 6 6]]


45. Flatten Nested List: Write a Python program to flatten a given nested list and convert it into a single-dimensional list.

In [50]:
number_list = [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
print('List: ',number_list)
new_number_list = []
for i in number_list:
    if type(i).__name__=='list':
        new_number_list.extend(i)
    else:
        new_number_list.append(i)
print('New List: ',new_number_list)

List:  [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
New List:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


46. List Element Frequency: Given a nested list containing lists of integers, write a Python program to count the frequency of each element in the entire nested list.

In [51]:
number_list = [1, [2, 3], [4, 1, 5], 2, [3, 6, 4, 2]]
print('List: ',number_list)
new_number_list = []
for i in number_list:
    if type(i).__name__=='list':
        new_number_list.extend(i)
    else:
        new_number_list.append(i)
print('New List(single): ',new_number_list)


count_val = len(new_number_list)
unique_number_list = []
count_number_list = []
i=0
while i<count_val:
    j=i+1
    count_number = 1
    if new_number_list[i]!=0:
        unique_number_list.append(new_number_list[i])
        while j<count_val:   
            if new_number_list[i]==new_number_list[j]:
                new_number_list[j]=0
                count_number+=1
            j+=1  
        new_number_list[i]=0
        count_number_list.append(count_number)
    i+=1
print('New List(unique): ',unique_number_list)
print('Count List: ',count_number_list)

List:  [1, [2, 3], [4, 1, 5], 2, [3, 6, 4, 2]]
New List(single):  [1, 2, 3, 4, 1, 5, 2, 3, 6, 4, 2]
New List(unique):  [1, 2, 3, 4, 5, 6]
Count List:  [2, 3, 2, 2, 1, 1]


47. Transpose Matrix: Write a Python program to transpose a given matrix represented as a nested list.

In [52]:
A = [[1,1,1],[2,2,2],[3,3,3]]
B = [[0,0,0],[0,0,0],[0,0,0]]
print('----A----') 
for i in range(0,3):
    for j in range(0,3):
        print(A[i][j],end=' ')
    print()
print('----transpose A----') 
i=0
while i<3:  
    j=0
    while j<3:
        B[j][i]=A[i][j]
        j+=1
    i+=1
for i in range(0,3):
    for j in range(0,3):
        print(B[i][j],end=' ')
    print()


----A----
1 1 1 
2 2 2 
3 3 3 
----transpose A----
1 2 3 
1 2 3 
1 2 3 


48. List of Lists Concatenation: Given a list of nested lists, write a Python program to concatenate all the sublists into a single flat list.

In [53]:
number_list = [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
print('List: ',number_list)
new_number_list = []
for i in number_list:
    if type(i).__name__=='list':
        new_number_list.extend(i)
    else:
        new_number_list.append(i)
print('New List: ',new_number_list)

List:  [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
New List:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# Tuple Problems

49. Tuple Concatenation: Write a Python program to concatenate two tuples and create a new tuple.

In [54]:
t1 = (1,2,3)
print(t1)
t2 = (4,5,6)
print(t2)
t3=t1+t2
print(t3)

(1, 2, 3)
(4, 5, 6)
(1, 2, 3, 4, 5, 6)


50. Tuple Unpacking: Given a tuple with three elements (x, y, z), write a Python program to unpack the tuple and assign the values to three variables.

In [55]:
t1 = (1,2,3)
x=t1[0]
y=t1[1]
z=t1[2]
print(x,'',y,'',z)

1  2  3


In [56]:
t1 = (1,2,3)
(x,y,z)=t1
print(x,'',y,'',z)

1  2  3


51. Tuple Sorting: Write a Python program to sort a tuple of integers in ascending order.

In [57]:
t1 = (5, 2, 24, 3, 1, 6, 7)  
t2 = tuple(sorted(t1))  
print('Tuple :', t1)  
print('Sorted Tuple :', t2)

Tuple : (5, 2, 24, 3, 1, 6, 7)
Sorted Tuple : (1, 2, 3, 5, 6, 7, 24)


52. Tuple Frequency Count: Given a tuple containing various elements, write a Python program to count the frequency of a specific element in the tuple.

In [58]:
t1 = (5, 3, 2, 3, 1, 2, 3)
count_val = 0
specific_val = 2
for i in t1:
    if i==specific_val:
        count_val+=1
print(specific_val,'is',count_val,'times')

2 is 2 times


53. Tuple to List: Write a Python program to convert a tuple into a list.

In [59]:
t1 = (5, 2, 24, 3, 1, 6, 7)  
print(t1)
print(type(t1))
li=list(t1)
print(li)
print(type(li))

(5, 2, 24, 3, 1, 6, 7)
<class 'tuple'>
[5, 2, 24, 3, 1, 6, 7]
<class 'list'>


54. Tuple Reversal: Write a Python program to reverse a tuple without using any built-in functions.

In [60]:
t1 = (5, 2, 24, 3, 1, 6, 7)  
t2 = tuple(reversed(t1))  
print('Tuple :', t1)  
print('reversed Tuple :', t2)

Tuple : (5, 2, 24, 3, 1, 6, 7)
reversed Tuple : (7, 6, 1, 3, 24, 2, 5)


55. Tuple Slicing: Given a tuple, write a Python program to extract a slice of elements from it.

In [61]:
t1 = (5, 2, 24, 3, 1, 6, 7)  
print(t1)
s1 = t1[0:2]
s2 = t1[2:5]
s3 = t1[-2:]
print(s1)
print(s2)
print(s3)

(5, 2, 24, 3, 1, 6, 7)
(5, 2)
(24, 3, 1)
(6, 7)


56. Tuple Operations: Given two tuples of integers, write a Python program to perform element-wise addition, subtraction, and multiplication and create new tuples for each operation.

In [62]:
t1 = (1,2,3)
print(t1)
t2 = (4,5,6)
print(t2)
add_list = []
sub_list = []
mul_list = []
for i in range(0,len(t1)):
    add_list.append(t1[i]+t2[i])
    sub_list.append(t1[i]-t2[i])
    mul_list.append(t1[i]*t2[i])
print('Addition',tuple(add_list))
print('Subtraction',tuple(sub_list))
print('multiplication',tuple(mul_list))

(1, 2, 3)
(4, 5, 6)
Addition (5, 7, 9)
Subtraction (-3, -3, -3)
multiplication (4, 10, 18)


In [63]:
t1 = (1,2,3)
print(t1)
t2 = (4,5,6)
print(t2)
print('Addition',tuple(map(lambda i, j: i + j, t1, t2)))
print('Subtraction',tuple(map(lambda i, j: i - j, t1, t2)))
print('multiplication',tuple(map(lambda i, j: i * j, t1, t2)))

(1, 2, 3)
(4, 5, 6)
Addition (5, 7, 9)
Subtraction (-3, -3, -3)
multiplication (4, 10, 18)


57. Tuple Membership Test: Write a Python program that takes an element as input and checks if it exists in a given tuple.

In [64]:
t1 = (5, 2, 24, 3, 1, 6, 7)  
print(t1)
#check_val = int(input('Type any above number: '))
check_val = 24
is_exist = False
for i in t1:
    if i==check_val:
        is_exist = True
        break
if is_exist:
    print(check_val,'is exist')
else:
    print(check_val,'is not exist')

(5, 2, 24, 3, 1, 6, 7)
24 is exist


58. Tuple Packing: Write a Python program to pack three variables into a single tuple and print the tuple.

In [65]:
x=10
y=20
z=30
t1 = (x,y,z)
print(t1)

(10, 20, 30)


# Nested List Problems

59. Nested List Element Access: Given a nested list, write a Python program to access and print specific elements from it.

In [66]:
number_list = [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
print('List: ',number_list)
print('Value 1: ',number_list[0])
print('Value 3: ',number_list[1][1])
print('Value 5: ',number_list[2][1])
print('Value 10: ',number_list[4][2])

List:  [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
Value 1:  1
Value 3:  3
Value 5:  5
Value 10:  10


60. Nested List Flattening: Write a Python program to flatten a nested list and convert it into a single-dimensional list.

In [67]:
number_list = [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
print('List: ',number_list)
new_number_list = []
for i in number_list:
    if type(i).__name__=='list':
        new_number_list.extend(i)
    else:
        new_number_list.append(i)
print('New List: ',new_number_list)

List:  [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
New List:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


61. Nested List Sorting: Given a nested list containing lists of integers, write a Python program to sort the sublists based on their lengths.

In [68]:
number_list = [1, [2, 3], [6, 4, 5], 7, [10, 8,9]]
print('List: ',number_list)
new_number_list = []
for i in number_list:
    if type(i).__name__=='list':
        j = sorted(i)
        new_number_list.append(j)
    else:
        new_number_list.append(i)
print('New List: ',new_number_list)

List:  [1, [2, 3], [6, 4, 5], 7, [10, 8, 9]]
New List:  [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]


62. List of Tuples Conversion: Given a nested list containing tuples of (x, y) coordinates, write a Python program to convert it into a list of x-coordinates and a list of y-coordinates.

In [69]:
number_list = [(1,2), (3, 4),(5,6), (7,8),(9,10)]
print(number_list)
x_list = []
y_list = []
for i in number_list:
    x_list.append(i[0])
    y_list.append(i[1])
print('list of x-coordinates: ',x_list)
print('list of y-coordinates: ',y_list)

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]
list of x-coordinates:  [1, 3, 5, 7, 9]
list of y-coordinates:  [2, 4, 6, 8, 10]


63. Matrix Transpose: Write a Python program to transpose a given matrix represented as a nested list.

In [70]:
A = [[1,1,1],[2,2,2],[3,3,3]]
B = [[0,0,0],[0,0,0],[0,0,0]]
print('----A----') 
for i in range(0,3):
    for j in range(0,3):
        print(A[i][j],end=' ')
    print()
print('----transpose A----') 
i=0
while i<3:  
    j=0
    while j<3:
        B[j][i]=A[i][j]
        j+=1
    i+=1
for i in range(0,3):
    for j in range(0,3):
        print(B[i][j],end=' ')
    print()

----A----
1 1 1 
2 2 2 
3 3 3 
----transpose A----
1 2 3 
1 2 3 
1 2 3 


64. Nested List Concatenation: Given a list of nested lists, write a Python program to concatenate all the sublists into a single flat list.

In [71]:
number_list = [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
print('List: ',number_list)
new_number_list = []
for i in number_list:
    if type(i).__name__=='list':
        new_number_list.extend(i)
    else:
        new_number_list.append(i)
print('New List: ',new_number_list)

List:  [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
New List:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


65. Count Even Numbers: Write a Python program to count the number of even numbers in a nested list.

In [72]:
number_list = [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
print('List: ',number_list)
even_count = 0
odd_count = 0
for i in number_list:
    if type(i).__name__=='list':
        for j in i:
            if j%2==0:
                even_count+=1
            else:
                odd_count+=1
    else:
        if i%2==0:
                even_count+=1
        else:
            odd_count+=1
print('Even count: ',even_count)
print('Odd count: ',odd_count)

List:  [1, [2, 3], [4, 5, 6], 7, [8, 9, 10]]
Even count:  5
Odd count:  5


66. Maximum Element in Nested List: Write a Python program to find the maximum element in a nested list of integers.

In [73]:
number_list = [110, [2, 330], [4, 55, 6], 77, [8, 9, 10]]
print('List: ',number_list)
max_val = 0
for i in number_list:
    if type(i).__name__=='list':
        for j in i:
            if max_val<j:
                max_val=j
    else:
        if max_val<i:
            max_val=i
print('Max Value: ',max_val)

List:  [110, [2, 330], [4, 55, 6], 77, [8, 9, 10]]
Max Value:  330


67. Diagonal Sum of Matrix: Given a square matrix represented as a nested list, write a Python program to calculate the sum of the elements in the main diagonal.

In [74]:
A = [[1,1,1],[2,2,2],[3,3,3]]
diagonal_sum=0
print('----A----') 
for i in range(0,3):
    for j in range(0,3):
        print(A[i][j],end=' ')
    print()
for i in range(0,3):
    for j in range(0,3):
        if i==j:
            diagonal_sum+=A[i][j]
print('Diagonal sum: ',diagonal_sum) 

----A----
1 1 1 
2 2 2 
3 3 3 
Diagonal sum:  6


68. Nested List Element Search: Write a Python program to search for a specific element in a nested list and return its position (row and column indices).

In [75]:
number_list = [110, [2, 330], [4, 55, 6], 77, [8, 9, 10]]
print('List: ',number_list)
#specific_element = int(input('Type any above number: '))
specific_element = 55
max_val = 0
r=0
row=0
c=0
column=0
for i in number_list:
    if type(i).__name__=='list':
        c=0
        for j in i:
            if specific_element==j:
                row=r
                column=c
                break
            c+=1
    else:
        if specific_element==i:
            row=r
            column=c
            break
    r+=1
print('Position : ',row+1,'row,',column+1,'column')

List:  [110, [2, 330], [4, 55, 6], 77, [8, 9, 10]]
Position :  3 row, 2 column


# Set Problems

69. Duplicate Removal: Write a Python program that takes a list of elements as input and creates a new set containing only the unique elements from the list.

In [76]:
number_list = [1,3,3,5,7,7,9]
print('List: ',number_list)
number_set = set(number_list)
print('Set: ',number_set)

List:  [1, 3, 3, 5, 7, 7, 9]
Set:  {1, 3, 5, 7, 9}


70. Set Intersection: Given two sets A and B, write a Python program to find their intersection and print the common elements.

In [77]:
A = {1,3,5,7,9}
print('Set A: ',A)
B = {2,3,4,7,8}
print('Set B: ',B)
C = A.intersection(B)
print('Set C: ',C)

Set A:  {1, 3, 5, 7, 9}
Set B:  {2, 3, 4, 7, 8}
Set C:  {3, 7}


71. Set Union: Given two sets A and B, write a Python program to find their union and print all the distinct elements from both sets.

In [78]:
A = {1,3,5,7,9}
print('Set A: ',A)
B = {2,3,4,7,8}
print('Set B: ',B)
C = A.union(B)
print('Set C: ',C)

Set A:  {1, 3, 5, 7, 9}
Set B:  {2, 3, 4, 7, 8}
Set C:  {1, 2, 3, 4, 5, 7, 8, 9}


72. Set Difference: Given two sets A and B, write a Python program to find the difference between set A and set B (i.e., elements present in A but not in B) and print the result.

In [79]:
A = {1,3,5,7,9}
print('Set A: ',A)
B = {2,3,4,7,8}
print('Set B: ',B)
C = A-B
print('Set C: ',C)

Set A:  {1, 3, 5, 7, 9}
Set B:  {2, 3, 4, 7, 8}
Set C:  {1, 5, 9}


73. Set Symmetric Difference: Given two sets A and B, write a Python program to find the symmetric difference between the two sets (i.e., elements that are present in either set A or set B, but not in both) and print the result.

In [80]:
A = {1,3,5,7,9}
print('Set A: ',A)
B = {2,3,4,7,8}
print('Set B: ',B)
C = (A-B).union(B-A)
print('Set C: ',C)

Set A:  {1, 3, 5, 7, 9}
Set B:  {2, 3, 4, 7, 8}
Set C:  {1, 2, 4, 5, 8, 9}


74. Set Operations: Given three sets A, B, and C, write a Python program to find and print the intersection of A and B, the union of B and C, and the difference between C and A.

In [81]:
A = {1,3,5,7,9}
print('Set A: ',A)
B = {2,3,4,7,8}
print('Set B: ',B)
C = {1,2,6,7,10}
print('Set C: ',C)
inter_sect = A.intersection(B)
print('intersection A and B: ',inter_sect)
union = B.union(C)
print('union B and C: ',union)
diff = C-A
print('difference C - A: ',diff)

Set A:  {1, 3, 5, 7, 9}
Set B:  {2, 3, 4, 7, 8}
Set C:  {1, 2, 6, 7, 10}
intersection A and B:  {3, 7}
union B and C:  {1, 2, 3, 4, 6, 7, 8, 10}
difference C - A:  {2, 10, 6}


75. Set Subset Check: Given two sets A and B, write a Python program to check if set A is a subset of set B and print the result.

In [82]:
A = {1,3,5,7,9}
print('Set A: ',A)
B = {3,7}
print('Set B: ',B)
print('A subset of B: ',A.issubset(B))

Set A:  {1, 3, 5, 7, 9}
Set B:  {3, 7}
A subset of B:  False


76. Set Superset Check: Given two sets A and B, write a Python program to check if set A is a superset of set B and print the result.

In [83]:
A = {1,3,5,7,9}
print('Set A: ',A)
B = {3,7}
print('Set B: ',B)
print('A superset of B: ',B.issubset(A))

Set A:  {1, 3, 5, 7, 9}
Set B:  {3, 7}
A superset of B:  True


77. Set Length Check: Write a Python program that takes a set as input and prints the number of elements in the set.

In [84]:
A = {1,3,5,7,9}
print('Set A: ',A)
print('Element of Set A: ',len(A))

Set A:  {1, 3, 5, 7, 9}
Element of Set A:  5


76. Set Membership Test: Write a Python program that takes an element as input and checks if it exists in a given set. Print “Found” if the element is present and “Not Found” otherwise.

In [85]:
A = {1,3,5,7,9}
print('Set A: ',A)
check_val = 5
is_exist = False
for i in A:
    if i==check_val:
        is_exist = True
if is_exist:
    print(check_val,'Found')
else:
    print(check_val,'Not Found')

Set A:  {1, 3, 5, 7, 9}
5 Found


# Dictionary Problems

77. Dictionary Manipulation: Given a dictionary with student names as keys and their corresponding scores as values, write a Python program to add a new student to the dictionary and update the score of an existing student.

In [86]:
std_dic = {'Abrar':75,'Fahad':85,'Hasan':55,'jahed':69}
print(std_dic)
#add
std_dic['Ahad']=72
print(std_dic)
std_dic.update({'Noman':49})
print(std_dic)
#update
std_dic['Fahad']=80
print(std_dic)
std_dic.update({'Hasan':78})
print(std_dic)

{'Abrar': 75, 'Fahad': 85, 'Hasan': 55, 'jahed': 69}
{'Abrar': 75, 'Fahad': 85, 'Hasan': 55, 'jahed': 69, 'Ahad': 72}
{'Abrar': 75, 'Fahad': 85, 'Hasan': 55, 'jahed': 69, 'Ahad': 72, 'Noman': 49}
{'Abrar': 75, 'Fahad': 80, 'Hasan': 55, 'jahed': 69, 'Ahad': 72, 'Noman': 49}
{'Abrar': 75, 'Fahad': 80, 'Hasan': 78, 'jahed': 69, 'Ahad': 72, 'Noman': 49}


78. Dictionary Keys and Values: Write a Python program that takes a dictionary as input and prints all the keys and values in separate lines.

In [87]:
emp_dic = {}
emp_list =['Abir','Manager','Sakib','Player','Fahad','Student']
#while True:
#    go = int(input('Want to entry(1/0): '))
#    if go:
#        key = input('Type name: ')
#        val = input('Type designation: ')
#        emp_dic[key]=val
#    else:
#        break

i=0     
while i<len(emp_list):
    key = emp_list[i]
    i = i + 1
    val = emp_list[i]
    i = i + 1
    emp_dic[key]=val



print('Keys: ',end=' ')
for key in emp_dic:
    print(key,end=',')

print()
print('Values: ',end=' ')
for key in emp_dic:
    print(emp_dic[key],end=',')


Keys:  Abir,Sakib,Fahad,
Values:  Manager,Player,Student,

79. Dictionary Length: Write a Python program to calculate and print the number of key-value pairs in a given dictionary.

In [88]:
std_dic = {'Abrar':75,'Fahad':85,'Hasan':55,'jahed':69}
print(std_dic)
print('Number of keyvalue pairs: ',len(std_dic))

{'Abrar': 75, 'Fahad': 85, 'Hasan': 55, 'jahed': 69}
Number of keyvalue pairs:  4


80. Dictionary Value Search: Given a dictionary of items and their prices, write a Python program to search for an item based on its price and print the item’s name.

In [89]:
item_dic = {'Chocolate':120,'Ice-Creame': 65,'Juice':80,'Pasta':150}
print(item_dic)
for item in item_dic:
    if item_dic[item]==65:       
        print('Search Item: ',item)
        break


{'Chocolate': 120, 'Ice-Creame': 65, 'Juice': 80, 'Pasta': 150}
Search Item:  Ice-Creame


81. Dictionary Merging: Given two dictionaries, write a Python program to merge them into a single dictionary and print the result.

In [90]:
item_dic_1 = {'Chocolate':120,'Ice-Creame': 65}
print(item_dic_1)
item_dic_2 = {'Juice':80,'Pasta':150}
print(item_dic_2)
#item_dic_1.update(item_dic_2)
item_dic_1 = item_dic_1 | item_dic_2
print(item_dic_1)

{'Chocolate': 120, 'Ice-Creame': 65}
{'Juice': 80, 'Pasta': 150}
{'Chocolate': 120, 'Ice-Creame': 65, 'Juice': 80, 'Pasta': 150}


82. Dictionary Key Removal: Given a dictionary of items and their quantities, write a Python program to remove a specific item from the dictionary based on user input.

In [91]:
item_dic = {'Chocolate':120,'Ice-Creame': 65,'Juice':80,'Pasta':150}
print(item_dic)
#del item_dic['Juice']
item_dic.pop('Juice')
print(item_dic)

{'Chocolate': 120, 'Ice-Creame': 65, 'Juice': 80, 'Pasta': 150}
{'Chocolate': 120, 'Ice-Creame': 65, 'Pasta': 150}


83. Dictionary Sorting: Given a dictionary with names as keys and corresponding ages as values, write a Python program to sort the dictionary based on age in ascending order.

In [92]:
cust_dic = {'Omar':25,'Amir':45,'Sakib':38,'Riyad':30}
print(cust_dic)
ages = list(cust_dic.values())
ages.sort()
cust_dic_sorted = {}
for i in ages:
    for key, val in cust_dic.items():
        if val ==i:
            cust_dic_sorted[key]=i
            break
print(cust_dic_sorted)

{'Omar': 25, 'Amir': 45, 'Sakib': 38, 'Riyad': 30}
{'Omar': 25, 'Riyad': 30, 'Sakib': 38, 'Amir': 45}


84. Dictionary Frequency Count: Write a Python program that takes a string as input and creates a dictionary containing each character as a key and its frequency as the value.

In [93]:
#str_inp = input('Type string: ')
str_inp = 'shihabshahid'
str_list = list(str_inp)
count_val = len(str_list)
char_count_dic = {}
i=0
while i<count_val:
    j=i+1
    count_number = 1
    if str_list[i]!=0:
        while j<count_val:   
            if str_list[i]==str_list[j]:
                str_list[j]=0
                count_number+=1
            j+=1 
        char_count_dic[str_list[i]]=count_number
        str_list[i]=0
    i+=1
print(char_count_dic)

{'s': 2, 'h': 4, 'i': 2, 'a': 2, 'b': 1, 'd': 1}


85. Dictionary Comprehension: Given a list of integers, write a Python program to create a dictionary where the keys are the elements from the list, and the values are their squares.

In [94]:
number_list = [1,2,3,4,5]
print(number_list)
number_sqr_dic = {i: i*i for i in number_list}
print(number_sqr_dic)

[1, 2, 3, 4, 5]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


86. Dictionary Key Check: Write a Python program that takes a key as input and checks if it exists in a given dictionary. Print “Key Found” if the key is present and “Key Not Found” otherwise.

In [95]:
cust_dic = {1:'Amir',2:'Sakib',3:'Kamal',4:'Riyad'}
#heck_key = int(input('Type key: '))
check_key = 3
is_exist = False
for key in cust_dic:
    if check_key==key:
        is_exist = True
if is_exist:
    print('Key Found')
else:
    print('Key not Found')


Key Found


# Nested Dictionary Problems

87. Access Nested Dictionary: Given a nested dictionary containing student details, write a Python program to access and print specific information such as a student’s name, age, and address.

In [96]:
std_dic = {
    'student1': {
        'name': 'Abir',
        'age': 20,
        'address': 'city'
    },
    'student2': {
        'name': 'Fahad',
        'age': 25,
        'address': 'dhk'
    },
    'student3': {
        'name': 'Hasan',
        'age': 22,
        'address': 'ctg'
    }
    
}
#print(std_dic)

#for i in std_dic:
#    print(i)
    
#for key, val in std_dic.items():
#    print(key,' ',val)
    
#for key, val in std_dic.items():
#    print(key)
#    for key, val in val.items():
#        print(key,' ',val)
 
    
for key, val in std_dic.items():
    print(key)
    print('----------')
    for key, val in val.items():
        print(key,' : ',val)
    print('==========')   
        
        

student1
----------
name  :  Abir
age  :  20
address  :  city
student2
----------
name  :  Fahad
age  :  25
address  :  dhk
student3
----------
name  :  Hasan
age  :  22
address  :  ctg


88. Nested Dictionary Length: Write a Python program to calculate and print the total number of key-value pairs in a nested dictionary.

In [97]:
std_dic = {
    'student1': {
        'name': 'Abir',
        'age': 20,
        'address': 'city'
    },
    'student2': {
        'name': 'Fahad',
        'age': 25,
        'address': 'dhk'
    },
    'student3': {
        'name': 'Hasan',
        'age': 22,
        'address': 'ctg'
    }
    
}
print('Total: ',len(std_dic))

for key,value in std_dic.items():
    print('Sub Total: ',len(value))

Total:  3
Sub Total:  3
Sub Total:  3
Sub Total:  3


89. Nested Dictionary Update: Given a nested dictionary of employee details, write a Python program to update an employee’s salary based on their employee ID.

In [98]:
emp_dic = {
    'person1': {
        'id':1,
        'name': 'Abir',
        'designation': 'manager',
        'salary': 30000
    },
    'person2': {
        'id':2,
        'name': 'Fahad',
        'designation': 'exicutive',
        'salary': 20000
    },
    'person3': {
        'id':3,
        'name': 'Hasan',
        'designation': 'sr. exicutive',
        'salary': 25000
    } 
}

for key, val in emp_dic.items():
    print(key)
    print('----------')
    for key, val in val.items():
        print(key,' : ',val)
    print('==========')
id = 0
for key, val in emp_dic.items():
    k=key
    for key, val in val.items():
        if val==2:
            id=val
        if id==2 and key=='salary':
            emp_dic[k][key] = val+val*.1 
print('----------id 2: salary updated------------')
for key, val in emp_dic.items():
    print(key)
    print('----------')
    for key, val in val.items():
        print(key,' : ',val)
    print('==========')

person1
----------
id  :  1
name  :  Abir
designation  :  manager
salary  :  30000
person2
----------
id  :  2
name  :  Fahad
designation  :  exicutive
salary  :  20000
person3
----------
id  :  3
name  :  Hasan
designation  :  sr. exicutive
salary  :  25000
----------id 2: salary updated------------
person1
----------
id  :  1
name  :  Abir
designation  :  manager
salary  :  30000
person2
----------
id  :  2
name  :  Fahad
designation  :  exicutive
salary  :  22000.0
person3
----------
id  :  3
name  :  Hasan
designation  :  sr. exicutive
salary  :  27500.0


90. Nested Dictionary Sorting: Given a nested dictionary containing product details (product name, price, and quantity), write a Python program to sort the products based on their prices in ascending order.

In [99]:
product_dic = {
    'product1': {
        'name': 'Cake',
        'price': 250,
        'quantity': 100
    },
    'product2': {
        'name': 'Ice Cream',
        'price': 150,
        'quantity': 200
    },
    'product3': {
        'name': 'Cheps',
        'price': 50,
        'quantity': 50
    },
    'product4': {
        'name': 'Juice',
        'price': 120,
        'quantity': 60
    },
}
print('-----original------')
print(product_dic)
#for key, val in product_dic.items():
#    print(key)
#    print('----------')
#    for key, val in val.items():
#       print(key,' : ',val)
#   print('==========')

sorted_dict = dict(sorted(product_dic.items(), key=lambda x: x[1]['price']))

print('-----sorted base price------')
print(sorted_dict)
#for key, val in sorted_dict.items():
#    print(key)
#    print('----------')
#    for key, val in val.items():
#        print(key,' : ',val)
#    print('==========')

-----original------
{'product1': {'name': 'Cake', 'price': 250, 'quantity': 100}, 'product2': {'name': 'Ice Cream', 'price': 150, 'quantity': 200}, 'product3': {'name': 'Cheps', 'price': 50, 'quantity': 50}, 'product4': {'name': 'Juice', 'price': 120, 'quantity': 60}}
-----sorted base price------
{'product3': {'name': 'Cheps', 'price': 50, 'quantity': 50}, 'product4': {'name': 'Juice', 'price': 120, 'quantity': 60}, 'product2': {'name': 'Ice Cream', 'price': 150, 'quantity': 200}, 'product1': {'name': 'Cake', 'price': 250, 'quantity': 100}}


91. Nested Dictionary Key Search: Write a Python program that takes a key as input and searches for it in a nested dictionary. If found, print the corresponding value, otherwise, print “Key Not Found.”

In [100]:
emp_dic = {
    'person1': {
        'id':1,
        'name': 'Abir',
        'designation': 'manager',
        'salary': 30000
    },
    'person2': {
        'id':2,
        'name': 'Fahad',
        'designation': 'exicutive',
        'salary': 20000
    },
    'person3': {
        'id':3,
        'name': 'Hasan',
        'designation': 'sr. exicutive',
        'salary': 25000
    } 
}

for key, val in emp_dic.items():
    print(key)
    print('----------')
    for key, val in val.items():
        print(key,' : ',val)
    print('==========')
print('----------Show salary search by id:  ------------')
#search_id = int(input('Type id: '))
search_id = 3
id = 0
is_exist = False
for key, val in emp_dic.items():
    k=key
    for key, val in val.items():
        if val==search_id:
            id=val
            is_exist = True
        if id==search_id and key=='salary' and is_exist:
            is_exist = False
            print('id: ',id,', Salary: ',val)
            break
if id==0:
    print('Not found')


person1
----------
id  :  1
name  :  Abir
designation  :  manager
salary  :  30000
person2
----------
id  :  2
name  :  Fahad
designation  :  exicutive
salary  :  20000
person3
----------
id  :  3
name  :  Hasan
designation  :  sr. exicutive
salary  :  25000
----------Show salary search by id:  ------------
id:  3 , Salary:  25000


# Break & Continue: 

92. Prime Number Checker: Write a Python program that takes a number as input and determines if it is a prime number or not. Use a `for` loop to check for factors. If a factor is found, `break` out of the loop.

In [101]:
#number = int(input('Type number: '))
number = 13
is_prime = True
for i in range(2,number):
    if number%i==0 and number!=2:
        is_prime = False
        break
if is_prime:
    print(number,' is prime number')
else:
    print(number,' is not prime number')


13  is prime number


93. Even Number Printer: Write a Python program to print all even numbers from 1 to 20. Use a `for` loop and `continue` to skip odd numbers.

In [102]:
for i in range(1,21):
    if i%2!=0:
        continue
    print(i,end=' ')

2 4 6 8 10 12 14 16 18 20 

94. Password Validator: Write a Python program that takes a password as input and checks if it meets the following criteria: at least 8 characters long, contains both uppercase and lowercase letters, and has at least one digit. If the password is valid, print “Password accepted.” If not, use `continue` to prompt the user to enter a valid password.

In [103]:
def is_eight_char(cl):
    if len(cl)>=8:
        return True
    return False
def is_upper_case(cl):
    for i in cl:
        if ord(i)>=65 and ord(i)<=89:
            return True
    return False
def is_lower_case(cl):
    for i in cl:
        if ord(i)>=97 and ord(i)<=122:
            return True
    return False
def is_number(cl):
    for i in cl:
        if ord(i)>=48 and ord(i)<=57:
            return True
    return False

#password = input('Type password: ')
password = 'Abcd@1234'
char_list = list(password)
if is_eight_char(char_list) and is_upper_case(char_list) and is_lower_case(char_list) and is_number(char_list):
    print('Password accepted')
else:
    print('Password not accepted')

Password accepted


95. Divisible by 3 or 5: Write a Python program to print all numbers from 1 to 50 that are divisible by either 3 or 5. Use a `for` loop and `continue` to skip numbers that are not divisible by either 3 or 5.

In [104]:
for i in range(1,51):
    if i%3==0 or i%5==0:
        print(i,end=',')
    else:
        continue

3,5,6,9,10,12,15,18,20,21,24,25,27,30,33,35,36,39,40,42,45,48,50,

96. Positive Number Sum: Write a Python program that takes positive numbers as input until a negative number is entered. Then, calculate and print the sum of all positive numbers entered. Use a `while` loop and `break` to exit the loop when a negative number is encountered.

In [105]:
num_list = [1,4,7,-8,3,5]
sum = 0
#while True:
#    number = int(input('Type number: '))
#    if number<0:
#        break
#    sum = sum + number
for number in num_list:
    if number<0:
        break
    sum = sum + number
print('Sum of all positive numbers: ',sum)

Sum of all positive numbers:  12


97. Word Palindrome Checker: Write a Python program that takes a word as input and checks if it is a palindrome (reads the same forwards and backward). Use `continue` to skip checking the word if its length is less than 3 characters.

In [106]:
#word = input('Type word: ')
word = 'shihab'
char_list = list(word)
if len(char_list)<3:
    print('Word is less than 3 char')
else:
    i = 0
    j = len(char_list)-1
    c = len(char_list)//2
    m = 0
    while i<c:
        if char_list[i]==char_list[j]:
            m=m+1
        i=i+1
        j=j-1
    if m==c:
        print('Palindrome')
    else:
        print('Not palindrome')

Not palindrome


98. Odd Number Finder: Write a Python program to find the first odd number from a list of integers. Use a `for` loop and `break` to stop the loop when the first odd number is found.

In [107]:
num_list = [4,8,9,6,3,2,10]
for i in num_list:
    if i%2!=0:
        print(i,' is first odd number')
        break

9  is first odd number


99. Number Guessing Game: Write a Python program that generates a random number between 1 and 100 and lets the user guess the number. Use a `while` loop, `break` when the correct number is guessed, and `continue` to keep prompting the user until they guess correctly.

In [108]:
from random import *
rand_num = randint(1, 100)
num_list = [i for i in range(1,101)]
print('Random: ',rand_num)
#while True:
#    number = int(input('Type Number: '))
#    if rand_num==number:
#        print('Correct number is guessed')
#        break;
for number in num_list:
    if rand_num==number:
        print('Correct number is guessed')
        break;

Random:  6
Correct number is guessed


100. Vowel Counter: Write a Python program that takes a string as input and counts the number of vowels (a, e, i, o, u) in it. Use a `for` loop and `continue` to skip counting non-vowel characters.

In [109]:
#text = input('Type text: ')
text = 'shihabshahid'
char_list = list(text)
c = 0
for i in char_list:
    if i=='a' or i=='e' or i=='i' or i=='o' or i=='u':
        c = c + 1
    else:
        continue
print('Number vowel: ',c)

Number vowel:  4


101. Unique Characters: Write a Python program that takes a string as input and checks if it contains all unique characters (no character repeats). Use a `for` loop and `break` when a character repeats.

In [110]:
#text = input('Type text: ')
text = 'abcd'
char_list = list(text)
c = 1
is_repeat = True
for i in char_list:
    j = c
    while j<len(char_list):
        if i==char_list[j]:
            print(i,' is contain repeated char')
            is_repeat = False
            break
        j = j + 1
    c = c + 1
if is_repeat:
    print(text,' is contain uniqe char')      

abcd  is contain uniqe char


# Functions Problems:

102. Factorial Calculator: Write a Python function called `factorial` that takes an integer as input and returns its factorial. Test the function with different values.

In [111]:
def factorial(n):
    if n<1:
        return 1
    else:
        return n*factorial(n-1)
#number = int(input('Type number: '))
number = 5
print(factorial(number))

120


103. Palindrome Checker: Write a Python function called `is_palindrome` that takes a string as input and returns `True` if it is a palindrome and `False` otherwise. Test the function with different words.

In [112]:
def is_palindrome(char_list):
    i = 0
    j = len(char_list)-1
    c = len(char_list)//2
    m = 0
    while i<c:
        if char_list[i]==char_list[j]:
            m=m+1
        i=i+1
        j=j-1
    if m==c:
        return True
    else:
        return False  
    
#word = input('Type word: ')
word = 'madam'
char_list = list(word)
if is_palindrome(char_list):
    print('Palindrome')
else:
    print('Not palindrome')

Palindrome


104. Even or Odd Checker: Write a Python function called `even_or_odd` that takes an integer as input and returns “Even” if the number is even and “Odd” if the number is odd. Test the function with different numbers.

In [113]:
def even_or_odd(n):
    if n%2==0:
        return True
    else:
        return False
#number = int(input('Type number: '))
number = 23
if even_or_odd(number):
    print('Even number')
else:
    print('Odd number')

Odd number


105. List Sum Calculator: Write a Python function called `list_sum` that takes a list of integers as input and returns the sum of all elements in the list. Test the function with different lists.

In [114]:
def list_sum(num_list):
    sum = 0
    for i in num_list:
        sum = sum + i
    return sum
num_list = [4,8,9,6,3,2,10]
print(list_sum(num_list))

42


106. Greatest Common Divisor (GCD) Calculator: Write a Python function called `gcd` that takes two integers as input and returns their greatest common divisor. Test the function with different pairs of numbers.

In [115]:
def gcd(n1,n2):
    if(n2 == 0):
        return n1
    else:
        return gcd(n2, n1 % n2)
#num_1 = int(input('Type number 1: '))
#num_2 = int(input('Type number 2: '))
num_1 = 60
num_2 = 48
print(gcd(60,48))

12


07. Leap Year Checker: Write a Python function called `is_leap_year` that takes a year as input and returns `True` if it is a leap year and `False` otherwise. Test the function with different years.

In [116]:
def check_leap(year): 
    if((year % 400 == 0) or (year % 100 != 0) and (year % 4 == 0)):   
        return True  
    else:
        return False 
#year = int(input('Type year: '))
year = 1700
if check_leap(year):
    print(year,' is leap year')
else:
    print(year,' is not leap year')

1700  is not leap year


# Nested Functions Problems:

108. Math Operations: Write a Python function called `math_operations` that takes three numbers and a string representing an operation (‘add’, ‘subtract’, ‘multiply’, or ‘divide’). The function should return the result of the specified operation on the three numbers. Implement the math operations as nested functions.

In [117]:
def math_operation(a,b,c,operation):
    def addition(a,b,c):
        print(a+b+c)
    def sbtraction(a,b,c):
        print(a-b-c)
    def multiplication(a,b,c):
        print(a*b*c)
    def division(a,b,c):
        print(a/b/c)
    def error():
        print('Error')
    if operation=='add':
        addition(a,b,c)
    elif operation=='subtract':
        sbtraction(a,b,c)
    elif operation=='multiply':
        multiplication(a,b,c)
    elif operation=='divide':
        division(a,b,c)
    else:
        error()
    
math_operation(5,8,2,'add')
math_operation(15,2,7,'subtract')
math_operation(5,2,2,'multiply')
math_operation(15,2,2,'divide')
math_operation(15,2,2,'equal')

15
6
20
3.75
Error


109. Greeting Generator: Write a Python function called `greeting_generator` that takes a name as input and returns a greeting message using nested functions. The greeting message should be customizable (e.g., “Hello, {name}! How are you today?”).

In [118]:
def greeting_generator(name):
    def get_name():
        return name
    print('Hello, ',get_name(),'! How are uyou today?')
greeting_generator('shihab')

Hello,  shihab ! How are uyou today?


110. Temperature Converter: Write a Python function called `temperature_converter` that takes a temperature value and a string representing the scale (‘C’ for Celsius or ‘F’ for Fahrenheit) as input. The function should convert the temperature from one scale to the other using nested functions and return the converted value.

In [119]:
def temperature_converter(p1,p2):
    def convert_celsius():
        return (p1-32) * 5/9
    def convert_fahrenheit():
        return (p1 * 9/5) + 32
    if p2=='c':
        print(p1,' fahrenheit = ',convert_celsius(),' = celsius')
    elif p2=='f':
        print(p1,' celsius = ',convert_fahrenheit(),' = fahrenheit')
    else:
        print('Error')
temperature_converter(68,'c')
temperature_converter(20,'f')

68  fahrenheit =  20.0  = celsius
20  celsius =  68.0  = fahrenheit


# Recursion

111. Factorial Calculation: Write a recursive Python function called `factorial` that takes a non-negative integer as input and returns its factorial.

In [120]:
def factorial(n):
    if n<1:
        return 1
    else:
        return n*factorial(n-1)
factorial(5)

120

112. Fibonacci Series: Write a recursive Python function called `Fibonacci` that takes an integer N as input and returns the Nth number in the Fibonacci series. The Fibonacci series is defined as follows: F(0) = 0, F(1) = 1, and F(n) = F(n-1) + F(n-2) for n > 1.

In [121]:
def fibonacci(n):
    if n <= 1:
        return n;
    return fibonacci(n - 1) + fibonacci(n - 2);
print(fibonacci(6))

8


113. The sum of Digits: Write a recursive Python function called `sum_of_digits` that takes an integer as input and returns the sum of its digits.

In [122]:
def sum_of_digit(n):
    if n<1:
        return 0;
    return n%10+sum_of_digit(n//10);
print(sum_of_digit(456))

15


114. Binary Search: Write a recursive Python function called `binary_search` that takes a sorted list and a target value as input and returns the index of the target value in the list using binary search. If the target value is not in the list, return -1.

In [123]:
def binary_search(L, start, end, item):  
    if end >= start:  
        middle = (start + end) // 2  
        if L[middle] == item:  
            return middle 
        elif L[middle] > item:   
            return binary_search(L, start, middle - 1, item)  
        else:  
            return binary_search(L, middle + 1, end, item)  
    else:  
        return -1  
    
my_list = [ 2, 4, 6, 9, 12, 16, 18, 19, 20, 21, 22 ]  
element_to_search = 9  
print("The given list is")  
print(my_list)  
  
index_of_element = binary_search(my_list, 0, len(my_list)-1, element_to_search)  
  
if index_of_element != -1:  
    print("Element searched is found at the index ", str(index_of_element), "of given list")  
else:  
    print("Element searched is not found in the given list!")  

The given list is
[2, 4, 6, 9, 12, 16, 18, 19, 20, 21, 22]
Element searched is found at the index  3 of given list


115. Power Calculation: Write a recursive Python function called `power` that takes two positive integers, base and exponent, as input and returns the value of base raised to the exponent.

In [124]:
def power(n, p):
    if p == 0:
        return 1
    return (n*power(n, p-1)) 
print(power(5, 2))

25
